### ISSUE TITLE
About 'automated .sublime-snippet generation'

### ISSUE THREAD

**Issue by yuntas** [jvcasill/R-snippets#8]
Mr. @jvcasill ,

Thank you for making many snippets.

If Program will make automatically `**.sublime-snippet` in the same time we'll doing `install.pacakge(**)`, we are so happy

**Comment by jvcasill** [comment]
Hi @yuntas 

I'm not sure I understand completely your question. Could you elaborate a bit more and I will look into making the relevant changes.
